name: CI/CD Pipeline for C# App

on:
  push:
    branches: [main]  # Run on every push to main
  pull_request:
    branches: [main]  # Run on every PR to main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.0'  # Change this based on your project .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal

  deploy:
    name: Deploy Application
    needs: build  # Runs only if build succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.0'

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      - name: Deploy (Example - FTP, AWS, Azure)
        run: echo "Deploying application..."
        # Here, you can add actual deployment steps like:
        # - Uploading to a server
        # - Deploying to Azure, AWS, or Docker
